name: Test Runner
on: [pull_request]
jobs:
  test-runner:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 'lts/*'

      - name: Install and Build
        run: |
          yarn install --frozen-lockfile
          yarn build
          ./packages/components/node_modules/cypress/bin/cypress install

      - name: Run unit tests
        run: yarn test

      # Dashboard integration tests
      - name: packages/dashboard integration tests
        uses: cypress-io/github-action@v2
        with:
          command: yarn test:cypress-ct
          working-directory: packages/dashboard
      - uses: actions/upload-artifact@v1
        if: failure()
        with:
          name: cypress-screenshots
          path: packages/dashboard/cypress/screenshots
      - uses: actions/upload-artifact@v1
        if: failure()
        with:
          name: cypress-videos
          path: packages/dashboard/cypress/videos
      - uses: actions/upload-artifact@v1
        if: failure()
        with:
          name: cypress-snapshots
          path: packages/dashboard/cypress/snapshots

      # Components integration tests
      - name: packages/components integration tests
        uses: cypress-io/github-action@v2
        with:
          command: yarn test:cypress-ct
          working-directory: packages/components
      - uses: actions/upload-artifact@v1
        if: failure()
        with:
          name: cypress-screenshots
          path: packages/components/cypress/screenshots
      - uses: actions/upload-artifact@v1
        if: failure()
        with:
          name: cypress-videos
          path: packages/components/cypress/videos
      - uses: actions/upload-artifact@v1
        if: failure()
        with:
          name: cypress-snapshots
          path: packages/components/cypress/snapshots

